app/models/Gallery.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "gallery".
 *
 * @property string $id
 * @property string $category_id
 * @property string $title
 * @property string $description
 * @property string $file_name
 * @property string $images_file
 * @property integer $num_view
 * @property integer $visible
 * @property integer $create_at
 *
 * @property Category $category
 */
class Gallery extends \yii\db\ActiveRecord
{
    public $imageFile;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gallery';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category_id', 'num_view', 'visible', 'create_at'], 'integer'],
            [['description', 'images_file'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['file_name'], 'string', 'max' => 50],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'مربوط به دسته',
            'title' => 'عنوان',
            'description' => 'توضیحات',
            'file_name' => 'نام فایل',
            'images_file' => 'عکسهای ذخیره شده',
            'num_view' => 'تعداد بازدید',
            'visible' => 'نمایش داده شود؟',
            'create_at' => 'زمان افزودن',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    public function getCategoryList()
    {
        return ArrayHelper::map(Category::findAll(['visible' => 1]), 'id', 'title');
    }
}

app/controllers/GalleryController.php
<?php
/**
 * Created by PhpStorm.
 * User: armin
 * Date: 6/27/2018
 * Time: 5:50 PM
 */

namespace app\controllers;


use app\models\Gallery;
use yii\web\Controller;

class GalleryController extends Controller
{
    public function actionIndex()
    {
        $model = Gallery::find()->orderBy(["id" => SORT_DESC])->all();
        $model2 = Gallery::find()->orderBy(["id" => SORT_ASC])->all();
        return $this->render('index', [
            'model' => $model,
            'model2' => $model2,
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        $model = Gallery::find()->where(['id' => $id])->one();
        $model->num_view =$model->num_view * 1  + 1  ;
        $model->save();

        return $this->render('view', [
            'model' => $model,


        ]);
    }
}

app/views/gallery/index.php
<?php
/**
 * Created by PhpStorm.
 * User: armin
 * Date: 6/26/2018
 * Time: 8:13 PM
 */

$this->registerCssFile('@web/storage/css/general/owl.carousel.css');
$this->registerCssFile('@web/storage/css/general/owl.theme.default.min.css');
$this->registerJsFile('@web/storage/js/general/owl.carousel.min.js',['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/storage/js/general/jquery.mousewheel.min.js',['depends' => [\yii\web\JqueryAsset::className()]]);
$this->title = 'گالری تصاویر - عمران سازه شمال';
$this->registerMetaTag([
    'name' => 'description',
    'content' => '',
]);
?>
<section>
    <div class="gallery-main">
        <div class="col-sm-10 col-sm-offset-1 gallery">
            <section id="demos">
                <div class="row">
                    <div class="owl-carousel owl-theme owl-rtl">
                    <?php
                    foreach ($model2 as $value):
                    ?>
                        <div class="item">
                            <div class="item-img">
                                <img  class="img-circle" src="<?= Yii::getAlias('@uploads-url').'/gallery/'.$value->file_name?>" alt="<?= $value->title;?>">
                            </div>
                            <h3><?= $value->title;?></h3>
                        </div>
                        <?php endforeach; ?>

                    </div>
                </div>
            </section>
        </div>
        <div class="col-sm-12">
            <div class="col-sm-1 label-item">
                <img  class="img-label" src="<?= Yii::getAlias('@storage-url').'/image/works.png'?>" alt="نمونه کارها">
            </div>
            <div class="col-sm-11 gallery-item">
                <div class="col-sm-11 works-item">
                    <?php
                    foreach ($model as $value):
                    ?>
                    <div class="col-sm-3">
                        <a href="<?= \yii\helpers\Url::to(['gallery/view',"id" => $value->id]);?>">
                        <div class="works-item-gallery">
                            <div class="works-image">
                                <img  class="" src="<?= Yii::getAlias('@uploads-url').'/gallery/'.$value->file_name?>" alt="<?= $value->title;?>">
                            </div>
                            <div class="work-title">
                                <h2><?= $value->title;?></h2>
                                <p><?= $value->description;?></p>
                            </div>
                        </div>
                        </a>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/gallery/view.php
<?php
/**
 * Created by PhpStorm.
 * User: armin
 * Date: 7/3/2018
 * Time: 3:57 PM
 *
/*  @var $model*/
$this->registerCssFile('@web/storage/css/general/fotorama.css');
$this->registerJsFile('@web/storage/js/general/fotorama.js', ['depends' => \yii\web\JqueryAsset::className()]);
$this->title = $model->title;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->description,
]);

 ?>
<section>
    <div class="row gallery-view">
            <div class="col-sm-8">
                <div class="main-news">
                    <a href="<?= \yii\helpers\Url::to(["gallery/index"])?>" class=" btn btn-danger">بازگشت</a>
                        <div class="news-title">
                            <h2><?= $model->title?> </h2>
                            <p><?= $model->description?></p>

                        </div>
                </div>
            </div>
        <div class="col-sm-4">
            <div class="property-slider">
                <div class="fotorama" data-nav="thumbs" data-autoplay="true" data-loop="true">
                    <?php
                    $images_file = json_decode($model->images_file);
                    foreach ($images_file as $item):
                        ?>
                        <a href="<?= Yii::getAlias('@uploads-url').'/gallery/'.$item;?>">
                            <img src="<?= Yii::getAlias('@uploads-url').'/gallery/'.$item;?>" alt="">
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>

        </div>
    </div>

</section>